# Site settings
title: 怎么又得起名字
email: jasper.ys.wang@gmail.com
url: "http://wyushi.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
gems:
    - jekyll-gist